spring.application.name=todo_list

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7simhpj2pic73fkngl0-a.oregon-postgres.render.com:5432/todo_db_vf3m
spring.datasource.username=todo_db_vf3m_user
spring.datasource.password=F1zSBL8Z1fJvInlya7Cxa0o3OhtRY9SJ

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary
cloudinary.cloud-name=drbkf0h0y
cloudinary.api-key=666649786376495
cloudinary.api-secret=snc9T0dmxakZNHbGk4qBUU4U3_g

# Port
server.port=${PORT:8080}